<?php

declare(strict_types=1);

$rthAutoloaderDepcrecated = DIR_FS_DOCUMENT_ROOT . '/vendor-no-composer/autoload.php';
$rthAutoloader = DIR_FS_DOCUMENT_ROOT . '/vendor-mmlc/autoload.php';

if (file_exists($rthAutoloader)) {
    require_once $rthAutoloader;
} elseif (file_exists($rthAutoloaderDepcrecated)) {
    require_once $rthAutoloaderDepcrecated;
} else {
    trigger_error(
        'MMLC Module composer/autoload notice: can`t find file: ' .
        $rthAutoloader . ' ' .
        ' This file is generated by the MMLC.',
        E_USER_NOTICE
    );
}
